name: snake-on-contribution-graph

on:
  push:  # Runs on any push event
  schedule: # Execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:  # Manually triggered

jobs:
  build:
    name: Jobs to update my contribution graph
    
    runs-on: ubuntu-latest
    steps:
      - name: checking out the repo
        uses: actions/checkout@v2
             
      - name: generating snake
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
      - name: ensure the generated files exist
        run: |
          ls dist
          test -f dist/github-snake.svg
          test -f dist/github-snake-dark.svg
          test -f dist/ocean.gif
          
      - name: deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
